<?php 
    header("X-Frame-Options: DENY");
    header("X-Frame-Options: SAMEORIGIN");
?>
<!DOCTYPE html>
<html lang="fr">
    
        <meta charset="UTF-8"/>
        <meta name="Club" content="Présentation"> 
        <title> LaForet </title>
        <link rel="stylesheet" type="text/css" href="../css/style.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js"></script>       
        <script type="text/javascript" src="../javascript/PDF.js" defer></script>
        <script type="text/javascript" src="../javascript/tri.js" defer></script>        
    