<nav>
    <ul>
        <li class="menu"><a href="index.html">Accueil</a></li>
        <li class="menu"><a href="lesBiens.php"> Les biens</a>
            <ul class="sub-menu">
                <li><a href=""> Maisons </a></li>
                <li><a href=""> Appartements </a></li>
                <li><a href=""> Locaux </a></li>
                <li><a href=""> Terrains nus </a></li>
                <li><a href=""> Immeubles </a></li>
            </ul>
        </li>
        <li class="menu"><a href="contact.html">Contact</a></li>
    </ul>
</nav>